repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: eeee35a
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: [ "--", "-A", "clippy::derive-partial-eq-without-eq" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: "README.md"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
